[pylint]
load-plugins = [
    "edulint.linting.checkers.short_problems",
    "edulint.linting.checkers.improper_loop",
    "edulint.linting.checkers.simplifiable_if",
    "edulint.linting.checkers.type_annotation_checker",
    "edulint.linting.checkers.basic_checker",
    "edulint.linting.checkers.duplication_checker",
    "edulint.linting.checkers.python_ta_checkers",
]
enable = [
    "missing-module-docstring",
    "missing-function-docstring",
    "missing-class-docstring",
    "use-implicit-booleaness-not-comparison",
    "unused-variable",
    "no-else-return",
    "unspecified-encoding",
    "superfluous-parens",
    "too-many-branches",
    "redefined-builtin",
    "too-many-statements",
    "too-many-arguments",
    "unused-argument",
    "too-many-return-statements",
    "inconsistent-return-statements",
    "invalid-name",
    "redefined-outer-name",
    "fixme",
    "consider-using-with",
    "no-name-in-module",
    "trailing-whitespace",
    "consider-using-in",
    "too-many-locals",
    "missing-final-newline",
    "simplifiable-if-statement",
    "chained-comparison",
    "useless-return",
    "no-else-break",
    "no-else-continue",
    "consider-using-dict-items",
    "too-many-boolean-expressions",
    "too-many-nested-blocks",
    "import-outside-toplevel",
    "unnecessary-comprehension",
    "assignment-from-no-return",
    "use-dict-literal",
    "unreachable",
    "consider-using-generator",
    "consider-using-f-string",
    "duplicate-value",
    "unnecessary-pass",
    "pointless-string-statement",
    "unsubscriptable-object",
    "simplifiable-if-expression",
    "consider-using-set-comprehension",
    "consider-using-max-builtin",
    "line-too-long",
    "undefined-loop-variable",
    "expression-not-assigned",
    "use-list-literal",
    "consider-iterating-dictionary",
    "redefined-argument-from-local",
    "pointless-statement",
    "no-member",
    "unnecessary-list-index-lookup",
    "syntax-error",
    "attribute-defined-outside-init",
    "bad-indentation",
    "useless-else-on-loop",
    "too-many-instance-attributes",
    "unneeded-not",
    "consider-swap-variables",
    "self-assigning-variable",
    "singleton-comparison",
    "dangerous-default-value",
    "undefined-variable",
    "self-cls-assignment",
    "use-a-generator",
    "eval-used",
    "modified-iterating-list",
    "consider-using-min-builtin",
    "use-implicit-booleaness-not-len",
    "unnecessary-dunder-call",
    "cell-var-from-loop",
    "trailing-newlines",
    "consider-using-join",
    "unnecessary-dict-index-lookup",
    "too-many-public-methods",
    "unidiomatic-typecheck",
    "unnecessary-lambda",
    "comparison-of-constants",
    "literal-comparison",
    "comparison-with-itself",
    "global-variable-undefined",
    "consider-using-ternary",
    "unpacking-non-sequence",
    "unused-private-member",
    "simplifiable-condition",
    "trailing-comma-tuple",
    "condition-evals-to-constant",
    "no-value-for-parameter",
    "broad-except",
    "implicit-str-concat",
    "too-many-lines",
    "consider-using-sys-exit",
    "non-ascii-name",
    "used-before-assignment",
    "using-constant-test",
    "no-self-argument",
    "disallowed-name",
    "global-statement",
    "ungrouped-imports",
    "use-sequence-for-iteration",
    "unsupported-binary-operation",
]
